# Generated by Django 4.2.7 on 2023-12-03 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Albergue', 'Albergue'), ('Cruce de arroyo', 'Cruce de arroyo'), ('Hospital', 'Hospital'), ('Bombero', 'Bombero'), ('Incidente', 'Incidente')], max_length=20)),
                ('latitud', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=8, max_digits=11)),
            ],
        ),
        migrations.CreateModel(
            name='Albergue',
            fields=[
                ('elemento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inicio.elemento')),
                ('ocupacion_actual', models.IntegerField()),
                ('ocupacion_total', models.IntegerField()),
                ('estado', models.CharField(choices=[('Verde', 'Verde'), ('Amarillo', 'Amarillo'), ('Rojo', 'Rojo')], max_length=20)),
                ('insumo_disponible', models.CharField(max_length=255)),
                ('suministro_electrico', models.BooleanField()),
                ('telefonos', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('elemento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inicio.elemento')),
                ('evento', models.CharField(max_length=255)),
                ('detalles', models.TextField()),
                ('fecha_hora', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Bombero',
            fields=[
                ('elemento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inicio.elemento')),
                ('suministro_electrico', models.BooleanField()),
                ('telefonos', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CruceArroyo',
            fields=[
                ('elemento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inicio.elemento')),
                ('estado', models.CharField(choices=[('Verde', 'Verde'), ('Amarillo', 'Amarillo'), ('Rojo', 'Rojo')], max_length=20)),
                ('suministro_electrico', models.BooleanField()),
                ('detalles', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('elemento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inicio.elemento')),
                ('estado', models.CharField(choices=[('Verde', 'Verde'), ('Amarillo', 'Amarillo'), ('Rojo', 'Rojo')], max_length=20)),
                ('insumo_disponible', models.CharField(max_length=255)),
                ('telefonos', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('elemento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inicio.elemento')),
                ('tipo', models.CharField(choices=[('Vía pública', 'Vía pública'), ('Carretera', 'Carretera')], max_length=20)),
                ('estado', models.CharField(choices=[('Verde', 'Verde'), ('Amarillo', 'Amarillo'), ('Rojo', 'Rojo')], max_length=20)),
                ('detalles', models.TextField()),
            ],
        ),
    ]
