# Generated by Django 4.2.7 on 2023-12-04 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_alter_albergue_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crucearroyo',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='crucearroyo',
            name='suministro_electrico',
        ),
        migrations.RemoveField(
            model_name='incidente',
            name='estado',
        ),
    ]
