# Generated by Django 4.2.7 on 2023-12-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_remove_crucearroyo_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='disponibilidad',
            field=models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], default='Baja', max_length=20),
        ),
    ]
