# Generated by Django 4.2.7 on 2023-12-04 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_hospital_disponibilidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albergue',
            name='insumo_disponible',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='insumo_disponible',
        ),
    ]
