# Generated by Django 4.2.7 on 2023-12-04 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_remove_albergue_insumo_disponible_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arroyo',
            fields=[
                ('elemento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inicio.elemento')),
                ('condicion', models.CharField(choices=[('Transitable', 'Transitable'), ('Transitar con precaución', 'Transitar con precaución'), ('No transitable', 'No transitable')], max_length=25)),
                ('detalles', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='CruceArroyo',
        ),
    ]
